# Use the Rest Client extension: REST Client
# Link: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

GET http://127.0.0.1:5555/api/population/state/:state/city/:city

###
# Test for city that exists
GET http://127.0.0.1:5555/api/population/state/Florida/city/Jacksonville

###
# Punctuation test for a city that exists
GET http://127.0.0.1:5555/api/population/state/coloRado/city/denveR

###
# Check for a state that doesn't exist
GET http://127.0.0.1:5555/api/population/state/Test/city/Fake

###
# Add a new state and city
PUT http://127.0.0.1:5555/api/population/state/Test/city/Fake23 
Content-Type: text/plain
  
99

###
# Overwrite an existing state and city
PUT http://127.0.0.1:5555/api/population/state/Florida/city/Orlando
Content-Type: text/plain
  
9001